### ISSUE TITLE
Menu : design api routes

### ISSUE THREAD

**Issue by nicolas-zozol** [robusta-code/kanteen#7]

**Comment by aleckvincent** [comment]
http://kanteen.com/api/menus <b>`GET`</b> - liste tous les menus
http://kanteen.com/api/menus <b>`POST`</b> - créer un menu ou le modifie
http://kanteen.com/api/menus/{id} <b>`GET`</b> - affiche un menu selon l'id
http://kanteen.com/api/menus/{id} <b>`DELETE`</b> - supprime un menu selon l'id
