### ISSUE TITLE
Privacy : design api routes

### ISSUE THREAD

**Issue by nicolas-zozol** [robusta-code/kanteen#9]

**Comment by eSRoye** [comment]
http://kanteen.com/user/privacy 
http://kanteen.com/admin/privacy
http://kanteen.com/admin/privacy/schoolreport
http://kanteen.com/admin/privacy/kanteenaccess
http://kanteen.com/admin/privacy/englishtrip
http://kanteen.com/admin/privacy/contract
http://kanteen.com/admin/privacy/pay

**Comment by aleckvincent** [comment]
http://kanteen.com/menu
